Database:
  Tipo: SQLITE #Tipos: MYSQL, SQLITE
  IP: localhost:3306
  DB: test
  User: admin
  Pass: ''
  Debug: true

# Configure o comando e as aliases de cada opção
# Comando principal
Comando:
  Comando: 'banco'
  Aliases: [ bank ]

#Coloque Legendchat, OpeNChat (ou nChat), UltimateChat, NoxusChat ou deixe Automatico para o auto-detect
Plugin de chat: 'Automatico'

# Tag do top banco
Tag: '&6[RICO]'

# Npc e holograma do banco
NPC:
  Skin: 'deliveryman'
  Altura: 3.1
  Holograma:
    - '&6&lBanco'
    - '&7Clique para abrir o banco.'
  Mensagens:
    Setado: '&a&lSUCESSO! &aNPC do banco setado com sucesso.'
    Removido: '&a&lSUCESSO! &aNPC do banco removido com sucesso.'
    Nao removido: '&c&lERRO! &aNPC do banco não está setado.'

# Mundos em que poderá morrer sem perder % do money.
# Tipo: BLACKLIST
Morrer blacklist:
  - 'Plot'

# Limites para saque e criação de cheques
Limites:
  Saque: 10
  Cheque: 10
  Resetar com: 60 # Em segundos

# Minimos para depositar, sacar e criar um cheque
Minimos:
  Saque: 2000.0
  Cheque: 2000.0
  Deposito: 1000.0

# Ativar o sistema de perder x % do money em mãos ao morrer.
# Porcentagens configuráveis na morrer.yml.
Perder ao morrer: true

# Quando o jogador realizar uma operação: depósito, saque ou criação de cheque, já salvar na database
Auto salvar: false

# Máximo de dinheiro que poderá render no banco
# deixe 0 para infinito
Render max: 0

# O dinheiro do banco dos jogadores irá render de acordo esta taxa
Selic:
  Ativar: true
  Valor: 1.8
  # segunda, terca, quarta, quinta, sexta, sabado, domingo, todos
  # dia-hora:minuto:segundo
  Horarios:
    - 'todos-9:00:00'
    - 'todos-9:11:00'

# O dinheiro do banco irá render de acordo a bolsa do yBolsa
Bolsa:
  Ativar: true
  Tempo: 30 # em segundos

# Item do cheque
Cheque:
  CustomSkull: false
  URL: ''
  ID: 339
  Data: 0
  Glow: true
  Name: '&aCheque de dinheiro'
  Lore:
    - ''
    - '&7Criado por: &a{player}&7.'
    - '&7Criado em: &f{data} &8- &f{hora}&7.'
    - ''
    - '&bValor do cheque: &a{money}&b.'
    - ''
    - '&7Clique com botão direito para ativar'

# Mensagens do plugin
Mensagens:
  Permissao: '&c&lERRO! &cVocê não tem permissão para fazer isto.'
  Cancelou: '&cVocê cancelou a operação.'
  Nao e numero: '&cO argumento não é um número.'
  Nao possui player: '&cVocê não possui a quantia &7{quantia}&c em mãos.'
  Nao possui banco: '&cVocê não possui a quantia &7{quantia}&c no banco.'
  Menor minimo: '&cEsta operação requer um mínimo de &7{quantia}&c.'
  Depositou: '&aVocê depositou &7{quantia}&a com sucesso.'
  Sacou taxa: '&aVocê sacou &7{quantia}&a com sucesso. &7Taxa: &8{taxa}%&7.'
  Sacou: '&aVocê sacou &7{quantia}&a com sucesso.'
  Criou taxa: '&aVocê criou um cheque de &7{quantia}&a com sucesso. &7Taxa: &8{taxa}%&7.'
  Criou: '&aVocê criou um cheque de &7{quantia}&a com sucesso.'
  Aguarde: '&cVocê atingiu seu limite diário desta operação, aguarde &7{tempo}&c para realizar essa operação novamente.'
  Inv cheio: '&cSeu inventário está cheio.'
  Ativou: '&aVocê ativou um cheque de &7{quantia}&a.'
  Jogador: '&cJogador {player} não encontrado.'
  Alterado: '&aDinheiro do banco do jogador &f{player} &aalterado para &f{money}&a.'
  Saldo player: '&aDinheiro que o jogador &f{player}&a possui no banco: &2R$ &f{money}&a.'
  Rendeu:
    - ''
    - '&aSeu dinheiro no banco rendeu!'
    - '&7Montante antigo: &c{antigo}&7.'
    - '&7Montate atual: &a{atual}&7.'
    - ''
    - '&bValor da selic: &7{selic}%&b.'
    - ''
  Depositar:
    - ''
    - '&aDigite no chat a quantia que quer depositar.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Sacar:
    - ''
    - '&aDigite no chat a quantia que quer sacar.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Sacar taxa:
    - ''
    - '&aDigite no chat a quantia que quer sacar.'
    - '&cVocê está pagando uma taxa de &7{taxa}%&c.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Cheque:
    - ''
    - '&aDigite no chat a quantia que quer criar um cheque.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Cheque taxa:
    - ''
    - '&aDigite no chat a quantia que quer criar um cheque.'
    - '&cVocê está pagando uma taxa de &7{taxa}%&c.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Rendeu bolsa:
    - ''
    - '&aSeu dinheiro no banco rendeu!'
    - '&7Montante antigo: &c{antigo}&7.'
    - '&7Montate atual: &a{atual}&7.'
    - ''
    - '&bValor da bolsa: &7{bolsa}%&b.'
    - ''

# As setas dos menus
Setas:
  # Voltar ao menu anterior
  Voltar:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&cVoltar'
    Lore:
      - '&7Clique para voltar ao menu anterior.'
  # Voltar a página anterior
  Anterior:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&cVoltar'
    Lore:
      - '&7Clique para voltar à página anterior.'
  # Ir para a próxima página
  Proximo:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&aPróxima'
    Lore:
      - '&7Clique para ir à próxima página.'